Document: nx-clock-applet
Title: Debian nx-clock-applet Manual
Author: <insert document author here>
Abstract: This manual describes what nx-clock-applet is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nx-clock-applet/nx-clock-applet.sgml.gz

Format: postscript
Files: /usr/share/doc/nx-clock-applet/nx-clock-applet.ps.gz

Format: text
Files: /usr/share/doc/nx-clock-applet/nx-clock-applet.text.gz

Format: HTML
Index: /usr/share/doc/nx-clock-applet/html/index.html
Files: /usr/share/doc/nx-clock-applet/html/*.html
